# src/deepaudit/scanners/static.py

def scan(ast_node, raw_code: str, file_path: str) -> list[dict]:
    """Performs static analysis to catch dangerous execution functions."""
    findings = []
    
    # Functions that should almost never be generated by an AI
    DANGEROUS_FUNCTIONS = {"eval(", "exec(", "os.system(", "subprocess.Popen("}
    
    lines = raw_code.splitlines()
    for i, line in enumerate(lines):
        line_clean = line.strip()
        
        # Ignore comments
        if line_clean.startswith("#"):
            continue
            
        for func in DANGEROUS_FUNCTIONS:
            if func in line_clean:
                findings.append({
                    "scanner": "StaticScanner",
                    "severity": "WARNING",
                    "line": i + 1,
                    "message": f"Dangerous dynamic execution function detected: '{func}'",
                    "snippet": line_clean
                })
    return findings