from pathlib import Path
from typing import Dict, Any

class MarkdownRenderer:
    def __init__(self, output_path: str):
        self.output_path = Path(output_path)
        # Ensure the vyne/docs directory exists
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

    def render(self, registry: Dict[str, Any]):
        """Generates the final Markdown file from the AST registry."""
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write("# 💎 Sapphire Collective: Vyne API Codex\n\n")
            f.write("> *Auto-generated by Vyne v0.3.0 Engine*\n\n")
            f.write("---\n\n")

            for file_path, data in registry.items():
                if not data["classes"] and not data["functions"]:
                    continue 

                clean_path = Path(file_path).relative_to(Path.cwd() / "src")
                f.write(f"## 📦 Module: `{clean_path}`\n\n")

                for cls in data["classes"]:
                    f.write(f"### Class: `{cls['name']}`\n\n") # Added blank line
                    f.write(f"{cls['doc']}\n\n")

                for func in data["functions"]:
                    params = func['params'] if func['params'] else "()"
                    # Changed to ### to satisfy MD001, and added \n\n for MD022
                    f.write(f"### `def {func['name']}{params}`\n\n")
                    f.write(f"{func['doc']}\n\n")